/**
 * Standardized audit actions for the File & Media Storage Engine.
 * Conforms to Phase 20.10 §4.
 */
export enum FileAssetAuditAction {
  UPLOAD_INITIATED = 'FILE_ASSET_UPLOAD_INITIATED',
  UPLOAD_COMPLETED = 'FILE_ASSET_UPLOAD_COMPLETED',
  UPLOAD_REJECTED = 'FILE_ASSET_UPLOAD_REJECTED',
  DOWNLOAD_URL_GENERATED = 'FILE_ASSET_DOWNLOAD_URL_GENERATED',
  DOWNLOAD_STARTED = 'FILE_ASSET_DOWNLOAD_STARTED',
  DOWNLOAD_COMPLETED = 'FILE_ASSET_DOWNLOAD_COMPLETED',
  DOWNLOAD_FAILED = 'FILE_ASSET_DOWNLOAD_FAILED',
  FILE_READ = 'FILE_ASSET_READ',
  FILE_UPDATED = 'FILE_ASSET_UPDATED',
  VISIBILITY_CHANGED = 'FILE_ASSET_VISIBILITY_CHANGED',
  CATEGORY_CHANGED = 'FILE_ASSET_CATEGORY_CHANGED',
  METADATA_UPDATED = 'FILE_ASSET_METADATA_UPDATED',
  PROCESSING_STARTED = 'FILE_ASSET_PROCESSING_STARTED',
  PROCESSING_COMPLETED = 'FILE_ASSET_PROCESSING_COMPLETED',
  PROCESSING_FAILED = 'FILE_ASSET_PROCESSING_FAILED',
  UPLOAD_FINALIZED = 'FILE_ASSET_UPLOAD_FINALIZED',
  UPLOAD_FAILED = 'FILE_ASSET_UPLOAD_FAILED',
  FILE_DELETED = 'FILE_ASSET_DELETED',
  FILE_RESTORED = 'FILE_ASSET_RESTORED',
  SIGNED_UPLOAD_URL_GENERATED = 'FILE_ASSET_SIGNED_UPLOAD_URL_GENERATED',
  SIGNED_DOWNLOAD_URL_GENERATED = 'FILE_ASSET_SIGNED_DOWNLOAD_URL_GENERATED',
  ACCESS_DENIED = 'FILE_ASSET_ACCESS_DENIED',
  SECURITY_VALIDATION_FAILED = 'FILE_ASSET_SECURITY_VALIDATION_FAILED',
}

/**
 * Standardized audit outcome status codes.
 * Conforms to Phase 20.10 §5.
 */
export enum FileAssetAuditOutcome {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
  DENIED = 'DENIED',
}
